### ISSUE TITLE
Any Suggestion on sending Rapid2 unlock code to the stimulator?

### ISSUE THREAD

**Issue by SallyWang9898** [armanabraham/Rapid2#2]
Hi. I'm using a rapid2 stimulator with software Version 11.0, and managed to obtain the unlock code from the manufacturer. However, I had some trouble regarding sending it to the stimulator.
Specifically, I’m confused with the CRC at the end of the unlock code. The code specific for our stimulator is ‘5f30-da26cd33-4d’, by adding the ‘Command’ it becomes ‘Q5f30-da26cd33-4d’. If I calculate one’s compliment CRC using all 17 bytes, it would be ‘01100110010’ in binary or 818 in decimal, too large to be sent in one byte. I noticed the last two bytes are indicated as MSB and LSB of unlock code CRC, respectively, but I didn’t quite understand it.
Any instructions would be extremely appreciated.
Also, it would be even better if you add a function of sending the unlock code to the stimulator into your toolbox.

my matlab code is:
```
serialPortObj = serial('COM1', 'BaudRate', 9600, 'DataBits', 8, 'StopBits', 1, 'Parity', 'none', 'FlowControl', 'none', 'Terminator', '?');
fopen(serialPortObj);
fprintf(serialPortObj, 'Q5f30-da26cd33-4d');
```

Thank you so much for reading this.

Sally Wang

**Comment by SallyWang9898** [comment]
Hi, I fixed this problem by now. For anyone with the same problem: 
The checksum for the whole command is the lower 8 bits of the one's compliment, in the case of decimal 818 (0x0332) this would be 0x32 or '2' in ascii, giving a final command string of ‘Q5f30-da26cd33-4d2’. 
Thanks for reading.

**Comment by armanabrahamyan** [comment]
Thanks @SallyWang9898 for posting a solution. If you find any other glitches, please post them.
